# Site settings

title: Perry's Test Page
header-img: img/home-bg.jpg
email: perrywmellis@user.noreply.gitub.com
description: "testtesttest"
baseurl: "/test_projectpage"
url: "http://perrywmellis.github.io"
github_username:  perrywmellis
project_repository: test_projectpage
disqus_shortname: test_projectpage

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
